spring:
  security:
    oauth2:
      client:
        registration:
          aad-b2c: # ClientAppAAD
            provider: aad-b2c-provider
            client-id: <client-id>
            client-secret: <secret>
            authorization-grant-type: authorization_code #client_credentials on_behalf_of 
            redirect-uri: http://localhost:8098/login/oauth2/code/aad-b2c #'{baseUrl}/login/oauth2/code/{registrationId}'
            scope: 
              - openid # id token
              #- offline_access # refresh token
              #- https://alao2b2c.onmicrosoft.com/1abe35a2-51cd-42a9-9a6f-ceab1c4e16b9/updateuser # access token for UserApiAAD resource
              #- https://alao2b2c.onmicrosoft.com/1abe35a2-51cd-42a9-9a6f-ceab1c4e16b9/readuser
        provider:
          aad-b2c-provider:
            authorization-uri: https://<tenantName>.b2clogin.com/<tenantName>.onmicrosoft.com/<user_flow>/oauth2/v2.0/authorize
            token-uri: https://<tenantName>.b2clogin.com/<tenantName>.onmicrosoft.com/<user_flow>/oauth2/v2.0/token
            jwk-set-uri: https://<tenantName>.b2clogin.com/<tenantName>.onmicrosoft.com/<user_flow>/discovery/v2.0/keys

server:
  port: 8098

logging:
  level:
    org:
      springframework:
        security: TRACE
