spring:
  security:
    oauth2:
      client:
        registration:
          aad-b2c:
            provider: aad-b2c-provider
            client-id: 6685ecd6-cacc-4738-8eac-7007aa78335d
            client-secret: RhG8Q~A9Q5C3EjgbHRfjgZEyHuBMUQCjFT34abt9
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8099/login/oauth2/code/aad-b2c #'{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          aad-b2c-provider:
            #issuer-uri: https://alao2b2c.b2clogin.com/5f2001c8-53b2-4a0b-9888-a14a809ee421/v2.0/
            authorization-uri: https://alao2b2c.b2clogin.com/alao2b2c.onmicrosoft.com/b2c_1_singin_singup_webapp2/oauth2/v2.0/authorize
            token-uri: https://alao2b2c.b2clogin.com/alao2b2c.onmicrosoft.com/b2c_1_singin_singup_webapp2/oauth2/v2.0/token
            jwk-set-uri: https://alao2b2c.b2clogin.com/alao2b2c.onmicrosoft.com/b2c_1_singin_singup_webapp2/discovery/v2.0/keys

#https://alao2b2c.b2clogin.com/alao2b2c.onmicrosoft.com/b2c_1_singin_singup_webapp2/v2.0/.well-known/openid-configuration
      
#spring:
#  cloud:
#    azure:
#      active-directory:
#        b2c:
#          enabled: true
#          base-uri: https://alao2b2c.b2clogin.com/alao2b2c.onmicrosoft.com/
#          credential:
#            client-id: 0ee5f048-259e-4b5a-aa64-39ebcd958e92
#            client-secret: 'ak_8Q~Fp14LWYJ2RnhpGaD_h86hzul-oWH1oKcgg'
#          login-flow: sign-up-or-sign-in
#          logout-success-url: http://localhost:8099
#          user-flows:
#            sign-up-or-sign-in: SignUpSignIn1
#            profile-edit: ProfileEditing1
#            password-reset: PasswordReset1
#          #user-name-attribute-name: <your-user-name-attribute-name> 

server:
  port: 8099